Modify Self Check item on README.md
TheOdinProject/css-exercises pull request #128
Opened 2022-01-31 03:18 UTC by LPRegen

- [x] I have thoroughly read and understand the [CSS Exercises Contributing Guide](https://github.com/TheOdinProject/css-exercises/blob/main/CONTRIBUTING.md)
- [x] The title of this PR is in `01 grid layout 1: Modify Self Check item on README.md.`

- [x] If one exists, I have linked a related open issue to this PR in Step 2 below

**1. Description of the Changes**
 
The fourth item on Self Check section was incorrect. It was stating "-The first column is three times larger than the other", when the second column should be three times larger than the first.

**2. Related Issue**

[Closes #120](https://github.com/TheOdinProject/css-exercises/issues/120)

2022-01-31 03:25 UTC, thatblindgeye requested changes
Thank you for making the fix and for the first time contribution! Just a couple of quick things: can you update the title of the PR to include the lesson this update is for, and can you uncomment the last checkbox so that is is visible?

2022-01-31 03:47 UTC, thatblindgeye approved these changes

2022-01-31 03:47 UTC, merged

2022-01-31 03:53 UTC, thatblindgeye commented
In the future for the `Closes #XXXX` line, you don't have to wrap the text in a link. So instead of `[Closes #120](....some url)` you'll want to just do `Closes #120`. Not a big deal in this case, but it just helps automate the process a little when it's properly linked. Thanks again for contributing! 🙂

2022-02-02 20:37 UTC, LPRegen commented
I just saw the comment, I will consider it for the next time. I thought it would be more useful link to the Issue.
Thanks you!