flex/06+07: Fix broken links
TheOdinProject/css-exercises pull request #160
Opened 2022-03-24 13:20 UTC by Micosaur

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01-flex-center: Update self check`

<hr>

**1. Because:**

Closes #154 & #155 

**2. This PR:**

- Fix broken link with href="#" to every anchor.

2022-03-26 11:52 UTC, thatblindgeye requested changes
So it looks like that descendant combinator file was included in this PR. Since you look to have used two difference branches, I'm wondering whether maybe you created this new flex-path-1 branch *from* that branch you made the descendant combinator update to.

Can you try bringing this branch up to date with the main branch of this repo?

2022-03-27 08:25 UTC, Micosaur commented
> So it looks like that descendant combinator file was included in this PR. Since you look to have used two difference branches, I'm wondering whether maybe you created this new flex-path-1 branch _from_ that branch you made the descendant combinator update to.
> 
> Can you try bringing this branch up to date with the main branch of this repo?

I think what had happened was, I followed the "Using Git in the Real World" guide from the contribution link on discord. And it had me merge the feature branch and the main together and maybe I've merged it the wrong way? Lol. But it should be fixed now, I think.

2022-03-27 14:07 UTC, thatblindgeye approved these changes

2022-03-27 14:07 UTC, thatblindgeye commented
Ah yeah it could be one of several things I'm sure. Thank you for making this update!

2022-03-27 14:07 UTC, merged