Cascade-fix: update for accessibility #188
TheOdinProject/css-exercises pull request #205
Opened 2022-07-26 12:09 UTC by Amandasilvbr

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `01-flex-center: Update self check`

Complete the following checkbox ONLY IF it is applicable to your PR. You can complete it later if it is not currently applicable:
-   [ ] I have ensured that the TOP solution files match the Desired Outcome image

<hr>

**1. Because:**

This pull request is for issue 188, which was necessary to make the exercise in question more visually accessible.

Closes #188

**2. This PR:**

* Had its font changed, so that the differentiation between the letter with weight 900 and 200 are more visible
* It had its colors changed by the font-weight property, so that the exercise is not only dependent on the color, which can affect the accessibility performance

**3. Additional Information:**

I've added a comment at the end of README.md explaining to old and new students why the change was made. In addition to clarifying this issue, the notice also seeks to encourage people to pay attention and be interested in this issue, which is not always taken into account in web development.

Also, I would like to make an addendum and leave a recommendation. Although one of the buttons has color, it is not the focus of the exercise, and was designed not to affect the vision of colorblind or low vision people. As you can see below:

![image](https://user-images.githubusercontent.com/100382936/181001285-e176538f-689b-4cdb-87c6-8aefdbcc9e57.png)

For comparison, here is an example of misuse of color, which is not accessible, because it has low contrast.:

![image](https://user-images.githubusercontent.com/100382936/181001632-bd0e8335-01fb-410c-bcf7-ea47783dde3b.png)

To whom it may concern, the name of this extension for accessibility is Accessibility Insights for Web.

I'm a Brazilian student, so if there are any spelling errors, please contact me.

2022-07-26 15:02 UTC, dm-murphy reviewed
Great work @Amandasilvbr and thanks for taking this issue on so quickly! 👍 

I liked your approach of using the `font-weight` instead of color. I also appreciated you retaining the button with green background and white lettering as an example of an accessible color option that passes WCAG standards. 

I left some comments in the review for you to look over when you get the chance. Please let me know if you have any questions. 

Also pinging @thatblindgeye to see if there are any other thoughts on this one.

2022-07-26 17:42 UTC, Amandasilvbr commented on foundations/06-cascade-fix/README.md
> +_Note: this exercise has had its style changed, for accessibility reasons. For new and old students, we propose to carry out the exercise noting how important it is to pay attention to the accessibil
Yes, it´s sound better!

2022-07-26 17:48 UTC, Amandasilvbr commented on foundations/06-cascade-fix/solution/solution.css
> +  font-weight: 900;
Thank you for bring me this information. I made some tests, and i will alternate te readme img with the weight 700 and 100.

2022-07-26 17:58 UTC, Amandasilvbr commented on foundations/06-cascade-fix/solution/solution.css
> +  font-weight: 900;
@dm-murphy , can you give me your opinion of the result, please? Do you think it's better the way it was before? I'm undecided, I don't know if it's still clear that the smaller paragraphs are bold.
![image](https://user-images.githubusercontent.com/100382936/181077990-56883ef5-178a-4d63-a22b-5cb6b2b0542d.png)

2022-07-27 15:41 UTC, dm-murphy commented on foundations/06-cascade-fix/solution/solution.css
> +  font-weight: 900;
Thanks @Amandasilvbr! I can distinguish the difference between the fonts here myself but agree it's less pronounced than before. Here's another idea, what about using an `800` value and labeling the text as "extra bold text". Would that be dark enough to make the smaller paragraph stick out better?

2022-07-29 12:16 UTC, Amandasilvbr commented on foundations/06-cascade-fix/solution/solution.css
> +  font-weight: 900;
Yes, @dm-murphy ! I made a test, and 800 is really better.

2022-07-29 12:29 UTC, Amandasilvbr commented on foundations/06-cascade-fix/solution/solution.css
> +  font-weight: 900;
I just made the last changes, if I'm missing something, let me know!

2022-07-30 14:04 UTC, dm-murphy requested changes
Thanks for the updates @Amandasilvbr! I believe I found a few missing "extra" words in the `solution.html` file so I added those as suggested commits which you can commit right from the comments. Other than that I think everything looks good! Thanks for all the iterations on this one! Your work is much appreciated 🙂

2022-07-30 14:04 UTC, dm-murphy commented on foundations/06-cascade-fix/solution/solution.html
> +      <div class="text child">I'm a smaller child div with bold text.</div>
```suggestion
      <div class="text child">I'm a smaller child div with extra bold text.</div>
```
**suggestion:** Adding the "extra" to the wording in the `solution.html`. You can commit these right from the comments if you'd like!

2022-07-30 14:04 UTC, dm-murphy commented on foundations/06-cascade-fix/solution/solution.html
> +    <p class="para small-para">I'm a smaller paragraph, also with bold text!</p>
```suggestion
    <p class="para small-para">I'm a smaller paragraph, also with extra bold text!</p>
```
**suggestion:** Adding the "extra" to the wording in the `solution.html`. You can commit these right from the comments if you'd like!

2022-07-31 19:46 UTC, dm-murphy approved these changes
Thanks @Amandasilvbr for the great work on this issue and all your help contributing to The Odin Project! 🎉

2022-07-31 19:46 UTC, merged