06-cascade-fix: Add missing weight from solution.css
TheOdinProject/css-exercises pull request #209
Opened 2022-08-01 01:19 UTC by JonathanRMartinezHernandez

[X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
[X] The title of this PR follows the `location of change: brief description of change` format, e.g. `01-flex-center: Update self check`

The solution.css has a font weight of 800 on the classes `.para, small-para`, `.small-para`, and `.child` that were missing from the originally assigned style.css

2022-08-03 16:15 UTC, typeofadam commented
Thank you for creating this pull request, I was confused by the fact you weren't meant to edit the styles themselves.

2022-08-04 16:45 UTC, dm-murphy commented
Hi @JonathanRMartinezHernandez 👋 

It looks like you submitted a pull request for your solution. Your solution should just stay on your local machine or your forked copy of the repository, but are not meant to be submitted to the original repository. Please read this section of our Contributing Guide about this: https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md#exercise-repos

Thanks and happy learning!

2022-08-04 17:26 UTC, JonathanRMartinezHernandez commented
Hi @dm-murphy ! 
Actually this is not the solution to the exercise, this was me trying to correct a typo or mistake.
Exercise 06 says that you have to make the provided .css file look like the image and the solutions.css _but_ you're not allowed to edit the the styles themselves so there's no way for this bold to appear, I believe, as according to the exercise's rules you cannot add `font-weight: 800;` yourself. 
This confused me and I asked for help in The Odin Project Discord server and people agreed that this was a mistake in the writing of the exercise and that a simple PR should fix it. This is my first Pull Request so I apologize if I did something wrong but either this style.ss should be fixed, or the solution.css and description of the exercise should be fixed

2022-08-04 18:15 UTC, dm-murphy commented
> Hi @dm-murphy ! Actually this is not the solution to the exercise, this was me trying to correct a typo or mistake. Exercise 06 says that you have to make the provided .css file look like the image and the solutions.css _but_ you're not allowed to edit the the styles themselves so there's no way for this bold to appear, I believe, as according to the exercise's rules you cannot add `font-weight: 800;` yourself. This confused me and I asked for help in The Odin Project Discord server and people agreed that this was a mistake in the writing of the exercise and that a simple PR should fix it. This is my first Pull Request so I apologize if I did something wrong but either this style.ss should be fixed, or the solution.css and description of the exercise should be fixed

Thanks for following up @JonathanRMartinezHernandez 🙏 

My mistake on closing this out. We get so many PRs that are solutions to the exercises and looking at the file changes it seemed like that's what this was!

For `06-cascade-fix` we just this week changed the exercise from using red and green text to using bold and thin text. It looks like we missed including these in the `style.css` too. So great catch! I think we will also need to add in the `thin` values to the file too. Going to give this a deeper look and will get back to you shortly. Thanks for the find and the PR!

2022-08-04 18:34 UTC, dm-murphy requested changes
@JonathanRMartinezHernandez 

I put in a suggested commit to add the missing property for the thin text. If you agree with that you can commit the suggested change right from the comment box. 

I believe that should be everything that is missing but let me know if you think anything else could be needed here!

Additionally I see there are old comments in the solution files that need to be updated. Since comments are hidden when viewing file changes they were previously missed. I can fix these in a separate PR.

2022-08-04 18:34 UTC, dm-murphy commented on foundations/06-cascade-fix/style.css
>    font-size: 22px;
```suggestion
  font-size: 22px;
  font-weight: 100;
```
**suggestion:** Adds the missing `font-weight` property for thin text.

2022-08-04 19:20 UTC, JonathanRMartinezHernandez commented
@dm-murphy You're right I had missed that one too! And it's not problem, I should've explained it a bit more more in the original post that I made. I'm glad that this could be caught and fixed

2022-08-04 19:40 UTC, dm-murphy approved these changes
Thanks again @JonathanRMartinezHernandez! Nice work 🎉

2022-08-04 19:40 UTC, merged